<?php

namespace LPSIO\PlateformeBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOffresParPage($page, $offreParPage)
    {
        $query = $this->createQueryBuilder('o')
            ->orderBy('o.dateCreation', 'DESC')
            ->getQuery();

        $query->setFirstResult(($page - 1) * $offreParPage)->setMaxResults($offreParPage);

        return new Paginator($query, true);
    }
}
